### ISSUE TITLE
maven 直接引用在匿名内部类中报class 不存在

### ISSUE THREAD

**Issue by linghuxiong** [houbb/opencc4j#8]
`
    public static void save2db(JSONArray tangs){
        DataSource dataSource = new SingleConnectionDataSource("XXXX","name","password",true);
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.batchUpdate("insert into Table(column1,column2,column3,column4,column5)VALUES(?,?,?,?,?)", new BatchPreparedStatementSetter() {

            @Override
            public void setValues(PreparedStatement preparedStatement, int i) throws SQLException {
                JSONObject tang = tangs.getJSONObject(i);
                preparedStatement.setString(1,tang.getString("aa"));
                preparedStatement.setString(2,tang.getString("bb"));
                //preparedStatement.setString(3,tang.getString("cc"));
                JSONArray paragraphs = tang.getJSONArray("dd");
                if(paragraphs != null && paragraphs.size() > 0){
                    String content = "";
                    for (int j = 0; j < paragraphs.size(); j++) {
                        content+=("<p>"+paragraphs.getString(j)+"<p>");
                    }
                    preparedStatement.setString(3,content);
                    preparedStatement.setString(4, ZhConverterUtil.toSimple(content));
                }else {
                    preparedStatement.setString(3,"");
                    preparedStatement.setString(4,"");
                }

                preparedStatement.setString(5,"aa");

            }

            @Override
            public int getBatchSize() {
                return tangs.size();
            }
        });
    }

}
`

异常信息：
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/houbb/heaven/support/instance/impl/Instances
	at com.github.houbb.opencc4j.util.ZhConverterUtil.<clinit>(ZhConverterUtil.java:27)
	at org.linghuxiong.poesy.input.TangInput$1.setValues(TangInput.java:57)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$batchUpdate$2(JdbcTemplate.java:944)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:647)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:936)
	at org.linghuxiong.poesy.input.TangInput.save2db(TangInput.java:42)
	at org.linghuxiong.poesy.input.TangInput.main(TangInput.java:32)
Caused by: java.lang.ClassNotFoundException: com.github.houbb.heaven.support.instance.impl.Instances
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more

**Comment by houbb** [comment]
缺失类 `ClassNotFoundException: com.github.houbb.heaven.support.instance.impl.Instances`，你用的 opencc4j 的版本是多少？

刚才自测了 1.4.0 版本没有这个问题。

（1）按理说上述包是默认引入的，请确认下是否有 heaven 版本的冲突。

（2）如果缺失 heaven 包，可以自己引入依赖：

```xml
<dependency>
    <groupId>com.github.houbb</groupId>
    <artifactId>heaven</artifactId>
    <version>0.1.70</version>
</dependency>
```

**Comment by linghuxiong** [comment]
后来发现是 jar 下不下来，后来好了，多谢
